version: "3"

services:
  web:
    container_name: api
    build: .
    command: /bin/sh ./startup.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks: 
  network-api:
    external:
      name: network-api