# Generated by Django 3.1.5 on 2021-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não responder')], default='P', max_length=1),
        ),
    ]
