# Generated by Django 3.1.5 on 2021-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='regiao',
            field=models.CharField(choices=[('AC', 'Águas Claras'), ('AS', 'Asa Sul'), ('AN', 'Asa Norte'), ('AR', 'Arniqueira'), ('BZ', 'Brazilandia'), ('CA', 'Candangolândia'), ('CI', 'Ceilândia'), ('CZ', 'Cruzeiro'), ('FE', 'Fercal'), ('GA', 'Gama'), ('GR', 'Guará'), ('IT', 'Itapoã'), ('JB', 'Jardim Botânico'), ('LS', 'Lago Sul'), ('LN', 'Lago Norte'), ('NB', 'Núcleo Bandeirante'), ('PW', 'Park Way'), ('PA', 'Paranoá'), ('Pl', 'Planaltina'), ('PP', 'Plano Piloto'), ('RE', 'Recanto das Emas'), ('RF', 'Riacho Fundo'), ('SA', 'Samambaia'), ('SM', 'Santa Maria'), ('SB', 'São Sabastião'), ('SCIA', 'SCIA'), ('RF', 'Riacho Fundo'), ('RF', 'Riacho Fundo II'), ('SI', 'SIA'), ('SO', 'Sobradinho'), ('SO', 'Sobradinho II'), ('SN', 'Sol Nascente'), ('SD', 'Sudoeste'), ('TA', 'Taguatinga'), ('VA', 'Varjão'), ('VP', 'Vicente Pires'), ('EO', 'Entre outros')], max_length=4),
        ),
    ]
