# Generated by Django 3.1.5 on 2021-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='produtividade',
            field=models.IntegerField(choices=[(1, 'Produtiva'), (0, 'Produtividade estavel'), (-1, 'Baixo rendimento')], default=False),
        ),
    ]
