# Generated by Django 3.1.5 on 2021-04-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('paciente', '0002_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.psicologo'),
        ),
    ]
