# Generated by Django 3.1.5 on 2021-04-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20210419_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(default=False, max_length=3, unique=True)),
                ('nome', models.CharField(max_length=90, verbose_name='NOME')),
                ('problemas', models.CharField(choices=[('C', 'Controlada'), ('M', 'Moderada'), ('G', 'Grave')], default=True, max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
