# Generated by Django 3.1.5 on 2021-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='problemas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='autoMedicacao',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='capacidadeDeSituaçõesDificeis',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='conhecimentoDoenca',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='convivioAmigos',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='convivioFamiliar',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='criseEspaçoInterior',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='energiaSono',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='estabilidadeDeEmoções',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exposiçãoRisco',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='humor',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='interessePelaVida',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='intoleranciaFrustração',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='maturidadeEmocional',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='problemasPessoais',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='qualidadeEscuta',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='qualidadeNutritiva',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='qualidadeSono',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tentativaSuicidio',
            field=models.IntegerField(choices=[(-1, 'Pior que antes'), (0, 'Sem mudança'), (1, 'Melhor que antes')], default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='registro',
            field=models.CharField(default=False, max_length=5, unique=True),
        ),
    ]
